glide:
    base_url: /image/resize
    source: '%kernel.project_dir%'
    cache: '%kernel.project_dir%/public/resized'
    pre_generate: '%env(bool:GLIDE_PRE_GENERATE_CACHE)%'
    cache_with_file_extensions: true
    group_cache_in_folders: true

    # https://glide.thephpleague.com/1.0/api/quick-reference/
    presets:
        game_list_cover:
            w: 1920
            h: 1080

        game_show_banner:
            h: 800
            q: 80

        game_show_screen:
            w: 1280

        game_show_thumbnails:
            w: 320
            h: 179
            q: 70

        game_show_official_cover:
            w: 150
            h: 200
            q: 80

        twitter_card_image:
            w: 1200
            h: 600
            q: 85

        opengraph_image:
            w: 1200
            h: 627
            q: 85
