twig:
    strict_variables: true
    default_path: '%kernel.project_dir%/templates'
    globals:
        site: "%site_parameters%"
        public_dir: "%kernel.project_dir%/public"
        blur_hash: '%env(bool:BLUR_HASH)%'
        ambiant_light: '%env(bool:AMBIANT_LIGHT)%'
